#pragma once

#include "SignatureScanner.h"
#include "JSONParser.h"
#include "Console.h"
#include <algorithm>
#include <cctype>
#include <string>

inline std::string ToLowerSignatureField(std::string value) {
    std::transform(value.begin(), value.end(), value.begin(), [](unsigned char character) {
        return static_cast<char>(std::tolower(character));
    });
    return value;
}

inline bool IsOptionalSignatureCategory(const std::string& category) {
    const std::string normalized = ToLowerSignatureField(category);
    return normalized == "library" || normalized == "runtime" || normalized == "thunk" || normalized == "auto";
}

inline bool IsOptionalSignatureImportance(const std::string& importance) {
    const std::string normalized = ToLowerSignatureField(importance);
    return normalized == "optional" || normalized == "experimental" || normalized == "informational";
}

inline SignatureResolver ToSignatureResolver(const SignatureEntry::Resolver& entryResolver) {
    SignatureResolver resolver;
    resolver.type = entryResolver.type;
    resolver.resultType = entryResolver.resultType;
    resolver.targetRva = entryResolver.targetRva;
    resolver.formula = entryResolver.formula;
    resolver.add = entryResolver.add;
    resolver.expected = entryResolver.expected;
    resolver.instructionOffset = entryResolver.instructionOffset;
    resolver.instructionSize = entryResolver.instructionSize;
    resolver.operandIndex = entryResolver.operandIndex;
    resolver.operandOffset = entryResolver.operandOffset;
    resolver.operandSize = entryResolver.operandSize;
    resolver.hasAdd = entryResolver.hasAdd;
    resolver.hasExpected = entryResolver.hasExpected;
    resolver.hasInstructionOffset = entryResolver.hasInstructionOffset;
    resolver.hasInstructionSize = entryResolver.hasInstructionSize;
    resolver.hasOperandIndex = entryResolver.hasOperandIndex;
    resolver.hasOperandOffset = entryResolver.hasOperandOffset;
    resolver.hasOperandSize = entryResolver.hasOperandSize;
    resolver.enabled = entryResolver.enabled;
    return resolver;
}

// Load signatures from a JSON file generated by the IDA script.
// Returns the number of signatures loaded, or -1 on error.
inline int LoadSignaturesFromJSON(SignatureScanner& scanner, const std::string& filepath) {
    std::vector<SignatureEntry> entries;
    std::string error;

    if (!JSONParser::LoadSignatures(filepath, entries, error)) {
        Console::PrintError(L"Failed to load signatures: " +
            std::wstring(error.begin(), error.end()));
        return -1;
    }

    int loaded = 0;
    int skipped = 0;

    for (const auto& entry : entries) {
        if (entry.pattern.empty()) {
            skipped++;
            continue;
        }

        const bool required = entry.hasRequiredFlag
            ? entry.required
            : !IsOptionalSignatureCategory(entry.category) && !IsOptionalSignatureImportance(entry.importance);
        const std::string importance = entry.importance.empty()
            ? (required ? "required" : "optional")
            : entry.importance;

        if (!scanner.AddSignatureFromIDA(
            entry.name,
            entry.pattern,
            entry.module,
            entry.rva,
            static_cast<intptr_t>(entry.addressOffset),
            entry.category,
            entry.quality,
            importance,
            entry.confidence,
            entry.sourceCount,
            entry.source,
            entry.sourceProject,
            entry.sourceUrl,
            required,
            ToSignatureResolver(entry.resolver),
            entry.resultType
        )) {
            skipped++;
            continue;
        }
        loaded++;
    }

    if (skipped > 0) {
        Console::PrintWarning(L"Skipped " + std::to_wstring(skipped) + L" entries (no pattern)");
    }

    return loaded;
}
