name: build

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify signatures
        shell: pwsh
        run: .\scripts\verify-signatures.ps1

      - name: Build
        shell: pwsh
        run: .\scripts\build.ps1 -Configuration Release -Platform x64 -Target scanner -PlatformToolset v143
